### PR TITLE
cake build 0.26.1 support

### LINKED ISSUE #58: Update Cake addin to Cake 0.26.0
Cake 0.26.0 introduced breaking changes in the API. The Cake addin should be built against Cake 0.26.0 to be compatible with current version

### PR DESCRIPTION
**Pull request by Jamie-Clayton**
- Updates the solution to support multi targeted output, including .net standard 2.0 required for cake build.
- Hopefully fixes problems reported at https://github.com/cake-contrib/Home/blob/master/Audit_for_Cake_0.26.0.md
- Unsure how the cake.build ILRepack works.
- No unit tests added, but https://github.com/cake-contrib/Cake.FileHelpers/tree/master/Cake.FileHelpers.Tests includes an interesting pattern that might be followed to ensure everything behaves.
- Closes #58.

### CODE REVIEW

**Comment by JenasysDesign** [comment]
@sergeyzwezdin Just curious if you had a chance to review this change? There are a few downstream projects using cake build and your addin, so it would be nice to bump the edition of cake.build that's supported.

**Comment by JenasysDesign** [comment]
@sergeyzwezdin bump. Would you mind reviewing the PR?

**Comment by santiagovm** [comment]
hi there, looking to use MagicChunks but noticed that latest stable version (2.0.0.119) is not compatible with Cake 0.26.

any chance to get this PR merged?

**Comment by Alex-Witkowski** [comment]
Would realy love to see this PR merged! @sergeyzwezdin can you please have a look at it?

**Comment by sergeyzwezdin** [comment]
@Alex-Witkowski I've merged it, but not actively working on the project right now.

**Comment by gep13** [comment]
@sergeyzwezdin is there anyway that we can help with this project to get a new release shipped? Happy to assist with this, just might need some pointers. Thanks again for this amazing library!

**Comment by sergeyzwezdin** [comment]
@gep13 Thank you! Well, there are problem with assembly (#71) and updating the project for Azure DevOps (#97). I planned to create separate organization and write it using .NET Standart + Node, and also implement it for all popular CI frameworks, but didn't have a time because of work. If you're ready to help at this stage (to resolve the current issues and make it working again), ping me by email/skype/telegram.

**Comment by pascalberger** [comment]
@sergeyzwezdin @gep13 I could also help maintaining it, especially the Cake addin part.

**Comment by gep13** [comment]
@sergeyzwezdin that is great news!  I will drop you an email just now.

**Pull request merged**
