### PR TITLE
Build against Cake 0.26.0

### LINKED ISSUE #58: Update Cake addin to Cake 0.26.0
Cake 0.26.0 introduced breaking changes in the API. The Cake addin should be built against Cake 0.26.0 to be compatible with current version

### PR DESCRIPTION
**Pull request by pascalberger**
Target .NET Standard 2.0 and build against Cake 0.26.0

Fixes #58

### CODE REVIEW

**Comment by pascalberger** [comment]
Build error seems to be because of AppVeyor image with incompatible NodeJS version for building the VSTS task and not related to these changes.

**Comment by pascalberger** [comment]
@sergeyzwezdin Any chance to get this merged?

**Comment by JenasysDesign** [comment]
Found a fix to the AppVeyor build failure in https://github.com/sergeyzwezdin/magic-chunks/pull/65/commits/ea3de89ff60b6cf7fce0ab0b18650fbd74e261e4. Interestingly I did a similar pull request for Magic chunks. See https://github.com/sergeyzwezdin/magic-chunks/pull/65

**Comment by pascalberger** [comment]
Was fixed with #65

**Pull request closed without merging**
